kind = "web"
previewPath = "/"
title = "WebsiteUpTest"
version = "1.0.0"
id = "artifacts/websiteuptest"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20061

[services.development]
run = "pnpm --filter @workspace/websiteuptest run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/websiteuptest", "run", "build" ]
publicDir = "artifacts/websiteuptest/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20061"
BASE_PATH = "/"
